### ISSUE TITLE
Use a manual Future impl for methods

### ISSUE THREAD

**Issue by yoshuawuyts** [smol-rs/async-channel#22]
I'm wrapping `Receiver::recv` and `Sender::send` in structs. Because they're `async fn` instead of manual Future impls they require boxing when stored. It'd be nice if we could expose two new types:

- `RecvFuture`
- `SendFuture`

These would not require boxing, which means they can be inlined in implementations and would increase overall perf when wrapping `async-channel`. Given the simplicity of `send` and `recv` I suspect the implementation to be rather straight forward.

Thanks!

**Comment by yoshuawuyts** [comment]
Ran into this again today; still stand by that this is a change we should implement.

**Comment by zserik** [comment]
This would probably require similarly exposed `Future` impls in `event-listener`.

**Comment by yoshuawuyts** [comment]
Filed a PR here: https://github.com/smol-rs/async-channel/pull/33
