### ISSUE TITLE
implement FusedStream for Receiver

### ISSUE THREAD

**Issue by zserik** [smol-rs/async-channel#3]
as `Receiver` can detect if the channel is `closed`, it probably can implement `FusedStream`...
see also [concurrent_queue::ConcurrentQueue::is_closed](https://docs.rs/concurrent-queue/1.1.1/concurrent_queue/struct.ConcurrentQueue.html#method.is_closed)

**Comment by zserik** [comment]
```rust
impl<T> FusedStream for Receiver<T> {
    fn is_terminated(&self) {
        self.channel.queue.is_closed()
    }
}
```

**Comment by stjepang** [comment]
I'm curious: in what cases is `FusedStream` useful or used in practice?

This sounds good - just a small correction: the `Receiver` is terminated when the queue is closed *and* is empty.

**Comment by zserik** [comment]
It is i.a. used for using the `futures::select!` macro without needing to `.fuse()` the `Stream`.

**Comment by zserik** [comment]
As `FusedStream` is defined in `futures-core`, this wouldn't even require another dependency. It would be a really small change which increases usability.
