### ISSUE TITLE
Equivalent to the Crossbeams `select!` macro?

### ISSUE THREAD

**Issue by d4h0** [smol-rs/async-channel#4]
Hi,

How would a user replace the `select!` macro of Crossbeam when using this library?

**Comment by stjepang** [comment]
Right now, there are `futures::select!` and `tokio::select!` but I'm not a big fan of either of those macros. I might come up with something in the future...

**Comment by d4h0** [comment]
Thanks, @stjepang!

So  `futures::select!` would be the only option if I want to create a runtime agnostic library.

Just out of curiosity: What do you not like about the `futures::select!` macro?

I'm not sure if you want to keep this issue open. Feel free to close it, if you like.

**Comment by stjepang** [comment]
@d4h0 `futures::select!` is implemented using procedural macros (slow compile times), sometimes gives poor errors without showing the exact error location, often requires you to bump `recursion_limit`, and requires you to call `.fuse()` when it could fuse futures on its own. I also don't think `complete =>` is a great idiom.

**Comment by d4h0** [comment]
Thanks for the information, @stjepang.

**Comment by d4h0** [comment]
Maybe it would be a good idea to mention `futures::select!` in the documentation?

I'm probably not the only async beginner who will be wondering what the equivalent to the Crossbeams `select!` macro is.

**Comment by notgull** [comment]
Nowadays you can use an [`or`](https://docs.rs/futures-lite/latest/futures_lite/future/fn.or.html) chain to emulate the `select!` macro.
