### ISSUE TITLE
[feature request] Add ability to send message to all channels (broadcast)

### ISSUE THREAD

**Issue by dignifiedquire** [smol-rs/async-channel#5]
It would be really great if it was possible to have a methods like `send_all`, and `try_send_all` such that it is easy to send messages to all `Receiver`s, not just a single one.

**Comment by yoshuawuyts** [comment]
This feature has come up in conversations on the mongodb rust driver as well.

cc/ @saghm I believe this feature would be the structural solution to runtime-agnostic multi-receiver channels you may looking for. Not quite sure how to implement this yet though, but that's something that can be looked into.

**Comment by andresv** [comment]
Do you happen to know a channel implementation that already has this feature?

**Comment by caelunshun** [comment]
A new crate has popped up with async broadcast channels: https://docs.rs/postage/0.4.0/postage/

**Comment by vladan** [comment]
@andresv maybe this one? https://github.com/filipdulic/bus-queue

**Comment by taiki-e** [comment]
@zeenix is working on this in https://github.com/smol-rs/async-broadcast.
