### ISSUE TITLE
Release with concurrent-queue 2.0.0 support

### ISSUE THREAD

**Issue by yodaldevoid** [smol-rs/async-channel#52]
The `bevy` project is currently waiting for a release of this project supporting `concurrent-queue` 2.0.0 due to the release of `async-executor` 1.5.0 also supporting `concurrent-queue` 2.0.0.

**Comment by taiki-e** [comment]
@sbarral @notgull: Is #49 ready for release? Or does it need some follow-up work? (If the latter it may need to be reverted once for release.)

**Comment by taiki-e** [comment]
Published v1.8.0.
