### ISSUE TITLE
awaited receiver is not awoken when messaged send into channel

### ISSUE THREAD

**Issue by GunnarMorrigan** [smol-rs/async-channel#54]
Hey guys,

I am writing an MQTT client that heavily uses channels for internal communication across Network <-> Handler <-> Client.
In some cases I saw that the client places a message into the channel to handler it is visible that there is a message if the length is checked but the Handler is not always awoken for the processing of the client request.

I Included an image here with some explanation.

![image](https://user-images.githubusercontent.com/13799935/207603528-33375341-4be0-4777-9c61-ce6a7de85a47.png)

This is a test function inside a library which runs on tokio multithreaded. 

What could be causing the receiver not to awake?

Thanks in advance

**Comment by notgull** [comment]
Do you have a code example of this happening? You shouldn't be polling the receiver in a tight loop like this.

**Comment by notgull** [comment]
Thanks! Also thanks for the diagram you made.

From a glance this seems to be either some kind of desync in `ConcurrentQueue` or the `Event` somehow dropping a notification, but I'd have to see the actual code to be sure.

**Comment by GunnarMorrigan** [comment]
> Thanks! Also thanks for the diagram you made.
> 
> From a glance this seems to be either some kind of desync in `ConcurrentQueue` or the `Event` somehow dropping a notification, but I'd have to see the actual code to be sure.

Thank you :) 

Having some trouble getting a very minimal reproduction. Basically it works as expected in a very basic case.
I could give you access to the repo, if this would be oke with you? 
It is a not yet published MQTT v5 client.

**Comment by GunnarMorrigan** [comment]
Ok, closing the issue a multi_threaded test case can only run one task at a time?
One task was very busy making sure that the other task was not getting any (or very little) time to run. Sometimes the initial start would allow the other task to arrive at the waiting point at just the right moment to make it all work.

Thank you @notgull for your response and willingness to help. I really like smol and the crates around it :).

**Comment by NingLin-P** [comment]
Hi @notgull, is this really an issue of `async-channl`? I saw https://github.com/smol-rs/async-channel/commit/51ab1273b46e29f88135b10629787d001b32d473 linked to this issue, is it fixed in v2.0.0? Asking because I'm debugging a problem and also suspect it is due to this issue.
