### ISSUE TITLE
`no_std` support

### ISSUE THREAD

**Issue by Xavrax** [smol-rs/async-channel#64]
Hello!
Are you guys planning to implement `no_std` support for this channel?

I know that it is currently blocked by https://github.com/smol-rs/event-listener/issues/61 but assume that it will be resolved soon.

I've checked the implementation and there are few decisions to be made (e.g. how to change `std::abort` - `panic`?) but this crates seems to be almost `no_std` ready. 
So my question is: did you plan to make such a move?

**Comment by notgull** [comment]
This will be closed by #59
